config/routes.rb
Rails.application.routes.draw do

  get 'suscriptors/new'

  mount Ckeditor::Engine => '/ckeditor'

  root 'landing_page#landing'

  get 'landing_page/about'

  get 'landing_page/wire_explanation'

  get 'landing_page/cancelar_cuenta'

  get 'landing_page/enterprise'

  get 'landing_page/contact'

  get 'suscriptors/contactpayment'

  get 'landing_page/privacyandterms'
  get 'landing_page/landing_corporate'
  get 'landing_page/landing_universities'

  devise_for :users

  resources :categories

  resources :tips

  resources :authors

  resources :strategies

  match '/404', via: :all, to: 'errors#not_found'
  match '/422', via: :all, to: 'errors#unprocessable_entity'
  match '/500', via: :all, to: 'errors#server_error'

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_and_belongs_to_many :strategies

  has_attached_file :image, styles: { medium: "300x300>", thumb: "150x150>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  validates :image_file_name, presence: true
  validates :name, presence: true
  validates :bio, presence: true
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  #layout "adminpanel"
  before_action :set_author, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :destroy, :create]
  layout :set_layout_by_role

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
      if current_user.admin?
        @author = Author.new
      else
       redirect_to strategies_path, alert: "no tienes derechos para crear autores"
      end
  end

  # GET /authors/1/edit
  def edit
     if current_user.admin?
      render "edit"
    else
      redirect_to strategies_path, notice: "no tienes derechos para editar este autor"
    end
  end

  # POST /authors
  # POST /authors.json
  def create
    if current_user.admin?
      @author = Author.new(author_params)

      respond_to do |format|
        if @author.save
          format.html { redirect_to @author, notice: 'Author was successfully created.' }
          format.json { render :show, status: :created, location: @author }
        else
          format.html { render :new }
          format.json { render json: @author.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    if current_user.admin?
      respond_to do |format|
        if @author.update(author_params)
          format.html { redirect_to @author, notice: 'Author was successfully updated.' }
          format.json { render :show, status: :ok, location: @author }
        else
          format.html { render :edit }
          format.json { render json: @author.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    if current_user.admin?
      @author.destroy
      respond_to do |format|
        format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      redirect_to strategies_url, notice: 'no tienes derechos para destruir esta estrategia'
    end
  end

  def set_layout_by_role
    if current_user.admin?
         "adminpanel"
       else
         "application"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:name, :bio, :image_url, :date, :image)
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.erb
<%= form_for @author, html: {multipart: true} do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="panel panel-info" style="text-align:left">
    <div class="panel-heading">
      <div class="panel-body" >
        <div class="field">
          <%= f.label :name %><br>
          <%= f.text_field :name %>
        </div>
        <div class="field">
          <%= f.label :bio %><br>
          <%= f.cktext_area :bio %>
        </div>

        <div class="field">
          <%= f.label :author_picture%><br>
          <p>make sure you upload a 100x100 image</p>
          <%= f.file_field :image %>
        </div>
        <div class="field">
          <%= f.label :date %><br>
          <%= f.date_select :date %>
        </div>
        <div class="actions">

         <p><%= link_to 'back to authors', authors_path, class: "btn btn-default" %><span>
          <%= f.submit 'save', class: "btn btn-success"%> </span>
        </p>
        </div>
      </div>
    </div>
  </div>

<% end %>

app/views/authors/edit.html.erb
<h1>Editing author</h1>

<%= render 'form' %>

app/views/authors/index.html.erb
<%= link_to 'Create new author', new_author_path, style:"float:right",class:"btn btn-success" %>
<h1>Listing authors</h1>

<table class="table table-condensed">
  <thead>
    <tr>
      <th>Picture</th>
      <th>Name</th>
      <th>Bio</th>
      <th>Created at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= image_tag author.image.url(:thumb),  size: "100x100", style: "border-radius: 50%" %></td>
        <td><%= author.name %></td>
        <td><%= author.bio.html_safe%></td>
        <td><%= author.date %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?, if you click ok you will erase this author from the data base' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/authors/new.html.erb
<h1>New author</h1>
<br>

<%= render 'form' %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= image_tag @author.image.url(:thumb), size: "100x100", style: "border-radius: 50%" %>
</p>

<p>
  <strong>Name:</strong>
  <%= @author.name %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @author.bio.html_safe %>
</p>

<p>
  <strong>Date:</strong>
  <%= @author.date %>
</p>

<%= link_to 'Edit', edit_author_path(@author),class: "btn btn-info" %> |
<%= link_to 'Back', authors_path,class: "btn btn-default" %>