config/routes.rb
Rails.application.routes.draw do

  get 'suscriptors/new'

  mount Ckeditor::Engine => '/ckeditor'

  root 'landing_page#landing'

  get 'landing_page/about'

  get 'landing_page/wire_explanation'

  get 'landing_page/cancelar_cuenta'

  get 'landing_page/enterprise'

  get 'landing_page/contact'

  get 'suscriptors/contactpayment'

  get 'landing_page/privacyandterms'
  get 'landing_page/landing_corporate'
  get 'landing_page/landing_universities'

  devise_for :users

  resources :categories

  resources :tips

  resources :authors

  resources :strategies

  match '/404', via: :all, to: 'errors#not_found'
  match '/422', via: :all, to: 'errors#unprocessable_entity'
  match '/500', via: :all, to: 'errors#server_error'

end

app/models/tip.rb
class Tip < ActiveRecord::Base
  belongs_to :strategy, touch: true
  validates :content, presence: true

end

app/controllers/tips_controller.rb
class TipsController < ApplicationController
  before_action :set_tip, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :destroy, :create]
  # GET /tips
  # GET /tips.json
  def index
    @tips = Tip.all
  end

  # GET /tips/1
  # GET /tips/1.json
  def show

  end

  # GET /tips/new
  def new
    @tip = Tip.new
  end

  # GET /tips/1/edit
  def edit
  end

  # POST /tips
  # POST /tips.json
  def create
    @tip = Tip.new(tip_params)

    respond_to do |format|
      if @tip.save
        format.html { redirect_to @tip, notice: 'Tip was successfully created.' }
        format.json { render :show, status: :created, location: @tip }
      else
        format.html { render :new }
        format.json { render json: @tip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tips/1
  # PATCH/PUT /tips/1.json
  def update
    respond_to do |format|
      if @tip.update(tip_params)
        format.html { redirect_to @tip, notice: 'Tip was successfully updated.' }
        format.json { render :show, status: :ok, location: @tip }
      else
        format.html { render :edit }
        format.json { render json: @tip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tips/1
  # DELETE /tips/1.json
  def destroy
    @tip.destroy
    respond_to do |format|
      format.html { redirect_to tips_url, notice: 'Tip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tip
      @tip = Tip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tip_params
      params.require(:tip).permit(:title, :content, :strategy_id)
    end
end

app/helpers/tips_helper.rb
module TipsHelper
end

app/views/tips/_form.html.erb
<%= form_for(@tip) do |f| %>
  <% if @tip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tip.errors.count, "error") %> prohibited this tip from being saved:</h2>

      <ul>
      <% @tip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div>
  <p> Seleccione la estrategia a la que pertenece este tip</p>
    <ul>
      <li><%= f.collection_check_boxes(:strategy_id, Strategy.all, :id, :title) %></li><br>
    </ul>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tips/edit.html.erb
<h1>Editing tip</h1>

<%= render 'form' %>

<%= link_to 'Show', @tip %> |
<%= link_to 'Back', tips_path %>

app/views/tips/index.html.erb
<h1>Listing tips</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Strategy</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tips.each do |tip| %>
      <tr>
        <td><%= tip.title %></td>
        <td><%= tip.content %></td>
        <td><%= tip.strategy %></td>
        <td><%= link_to 'Show', tip %></td>
        <td><%= link_to 'Edit', edit_tip_path(tip) %></td>
        <td><%= link_to 'Destroy', tip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tip', new_tip_path %>

app/views/tips/new.html.erb
<h1>New tip</h1>

<%= render 'form' %>

<%= link_to 'Back', tips_path %>

app/views/tips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @tip.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @tip.content %>
</p>

<p>
  <strong>Strategy:</strong>
  <%= @tip.strategy %>
</p>

<%= link_to 'Edit', edit_tip_path(@tip) %> |
<%= link_to 'Back', tips_path %>