config/routes.rb
Rails.application.routes.draw do

  get 'suscriptors/new'

  mount Ckeditor::Engine => '/ckeditor'

  root 'landing_page#landing'

  get 'landing_page/about'

  get 'landing_page/wire_explanation'

  get 'landing_page/cancelar_cuenta'

  get 'landing_page/enterprise'

  get 'landing_page/contact'

  get 'suscriptors/contactpayment'

  get 'landing_page/privacyandterms'
  get 'landing_page/landing_corporate'
  get 'landing_page/landing_universities'

  devise_for :users

  resources :categories

  resources :tips

  resources :authors

  resources :strategies

  match '/404', via: :all, to: 'errors#not_found'
  match '/422', via: :all, to: 'errors#unprocessable_entity'
  match '/500', via: :all, to: 'errors#server_error'

end

app/views/layouts/_dashboardheader.html.erb
<body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Innovation Lessons Panel", strategies_path, class: "navbar-brand active" %>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">

              <li ><%= link_to "Strategies", strategies_path, class: "active"%></li>
              <li><%= link_to "Authors", authors_path %></li>
              <li><%= link_to "Categories", categories_path %></li>
              <% if  user_signed_in? %>
                 <li><%= link_to "log out", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-off" %></li>
                <% else %>
                <li><%= link_to"iniciar sesión", new_user_session_path%></li>
              <% end %>

          </ul>


                <div class="input-group" style="margin-top: 9px; width:45%" >
                  <%= form_tag(strategies_path, :method => "get", id: "search-form", class: "input-group-btn") do %>
                    <div class="input-group">
                      <%= text_field_tag :keyword, params[:keyword], autofocus: true, placeholder: "buscar...", class: "form-control" %> <span class="input-group-btn">
                      <%= submit_tag("buscar", class: "btn btn-default") %>
                      </span>

                    </div>

                  <% end %>
                </div>


        </div>
      </div>
    </nav>

app/views/layouts/_error_to_render.html.erb
    <nav class="navbar navbar-inverse navbar-fixed-top" style="background-color: white">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar" style="background-color: #72c02c">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <% if user_signed_in? %>
            <%=link_to "Innovation Lessons", strategies_path , class: "navbar-brand", style: "color:#72c02c" %>
          <% else %>
            <%=link_to "Innovation Lessons", root_path , class: "navbar-brand", style: "color:#72c02c" %>
          <%end%>
        </div> <!-- nav-header -->

        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <% unless user_signed_in? %>
              <li><%= link_to"Para Empresas", landing_page_enterprise_path, id: "text-nav-bar"%></li>
              <li><%= link_to"Iniciar Sesión", new_user_session_path, id: "text-nav-bar"%></li>
              <li><%= link_to"Suscribirme", new_user_registration_path, id: "text-nav-bar" %></li>
            <% end %>
            <% if user_signed_in? %>
              <li class="dropdown">
                <%#= link_to,'#', current_user.name,  %>
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span>Mi cuenta <strong class="caret"></strong></a>

                <ul class="dropdown-menu">
                <!--<li>
                  <a href="#"><span class="glyphicon glyphicon-wrench"></span> Configuración</a>
                </li> -->

                  <li><%= link_to " actualizar perfil", edit_user_registration_path, class: "glyphicon glyphicon-refresh"  %></li>

                  <li class="divider"></li>

                  <li><%= link_to " cerrar sesión", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-off" %></li>

                </ul>
              </li>
            <% end %>
          </ul>

        </div> <!-- #id=navbar -->
      </div><!-- container-fluid -->
    </nav><!-- nav -->

app/views/layouts/_header.html.erb
    <nav class="navbar navbar-inverse navbar-fixed-top col-md-12" style="background-color: black" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar" style="background-color:#46b8da">
            <span class="sr-only" >Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <% if user_signed_in? %>
            <%=link_to "Nayib Abdalá", strategies_path , class: "navbar-brand", style: "color:#46b8da" %>
          <% else %>
            <%=link_to "Nayib Abdalá", root_path , class: "navbar-brand", style: "color:#46b8da" %>
          <%end%>
        </div> <!-- nav-header -->

        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">

            <% unless user_signed_in? %>
              <li><%= link_to"iniciar sesión", new_user_session_path, id: "text-nav-bar"%></li>
              <li><%= link_to"suscribirme", new_user_registration_path, id: "text-nav-bar"%></li>

              <!--<li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Servicios <strong class="caret"></strong></a>

                  <ul class="dropdown-menu">
                    <li>
                      <a href="#">servicio básico</a>
                    </li>

                    <li>
                      <a href="#">servicio pro</a>
                    </li>
                  </ul> end dropdown-menu -->
            <% end %>
            <% if user_signed_in? %>
              <li class="dropdown">
                <%#= link_to,'#', current_user.name,  %>
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" style= "color:#46b8da"><span class="glyphicon glyphicon-user"></span>Mi cuenta <strong class="caret"></strong></a>

                <ul class="dropdown-menu">
                <!--<li>
                  <a href="#"><span class="glyphicon glyphicon-wrench"></span> Configuración</a>
                </li> -->

                  <li><%= link_to " actualizar perfil", edit_user_registration_path, class: "glyphicon glyphicon-refresh", style: "color:#46b8da"  %></li>

                  <li class="divider"></li>

                  <li><%= link_to " cerrar sesión", destroy_user_session_path, style: "color:#46b8da",  method: :delete, class: "glyphicon glyphicon-off" %></li>

                </ul>
              </li>
            <% end %>
          </ul>


        <%= form_tag(strategies_path, :method => "get", id: "search-form") do %>
          <div class="input-group" style="margin-top: 9px" >
            <%= text_field_tag :keyword, params[:keyword], autofocus: true, placeholder: "escribe palabras relacionadas con lo que quieres aprender", class: "form-control"%>
            <span class="input-group-btn">
            <%= submit_tag("buscar", class: "btn btn-default") %>
            </span>
          </div>
      <% end %>


        </div> <!-- #id=navbar -->
      </div><!-- container-fluid -->
    </nav><!-- nav -->

<!-- <div >
          <div class="input-group" style="margin-top: 9px">
            <input type="text" class="form-control" placeholder="de que quieres aprender hoy...">
            <span class="input-group-btn">
              <button class="btn btn-default" type="button">buscar!</button>
            </span>
          </div>/input-group -->

app/views/layouts/_landing_nav.html.erb
    <nav class="navbar navbar-inverse navbar-fixed-top col-md-12" style="background-color: black" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar" style="background-color:#46b8da">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <% if user_signed_in? %>
            <%=link_to "Nayib Abdalá", strategies_path , class: "navbar-brand", style: "color:#46b8da" %>
          <% else %>
            <%=link_to "Nayib Abdalá", root_path , class: "navbar-brand", style: "color:#46b8da" %>
          <%end%>
        </div> <!-- nav-header -->

        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <% unless user_signed_in? %>
              <li><%= link_to"Para Empresas", landing_page_landing_corporate_path, id: "text-nav-bar"%></li>
              <li><%= link_to"Para Universidades", landing_page_landing_universities_path, id: "text-nav-bar"%></li>
              <li><%= link_to"Iniciar Sesión", new_user_session_path, id: "text-nav-bar"%></li>
              <li><%= link_to"Suscribirme", new_user_registration_path, id: "text-nav-bar" %></li>
            <% end %>
            <% if user_signed_in? %>
              <li class="dropdown">
                <%#= link_to,'#', current_user.name,  %>
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span>Mi cuenta <strong class="caret"></strong></a>

                <ul class="dropdown-menu">
                <!--<li>
                  <a href="#"><span class="glyphicon glyphicon-wrench"></span> Configuración</a>
                </li> -->

                  <li><%= link_to " actualizar perfil", edit_user_registration_path, class: "glyphicon glyphicon-refresh"%></li>

                  <li class="divider"></li>

                  <li><%= link_to " cerrar sesión", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-off" %></li>

                </ul>
              </li>
            <% end %>
          </ul>

        </div> <!-- #id=navbar -->
      </div><!-- container-fluid -->
    </nav><!-- nav -->

<!-- <div >
          <div class="input-group" style="margin-top: 9px">
            <input type="text" class="form-control" placeholder="de que quieres aprender hoy...">
            <span class="input-group-btn">
              <button class="btn btn-default" type="button">buscar!</button>
            </span>
          </div>/input-group -->

app/views/layouts/adminpanel.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewIlApp</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<br><br><br>

<%= render 'layouts/dashboardheader' %> <br>

<div class="container">
  <% flash.each do |name, msg| %>
     <%= content_tag(:div, msg, class: "alert alert-warning") %>
  <% end %>
</div>

     <div class="container">
        <div class="page-header">
          <h4>Platform Administration</h4>
          <p>Welcome to the ContentManager pannel. Chose from the menu in the bar above to create, edit, update and delete strategies, authors or categories.</p>
        </div>
      </div>
      <div class="container">

           <%= yield %>


      </div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewIlApp</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


</head>
<body>

  <br><br><br>
    <%= render 'layouts/header' %>


  <% flash.each do |name, msg| %>
     <%= content_tag(:div, msg, class: "alert alert-success") %>
  <% end %>


<%= yield %>


</body>
</html>

app/views/layouts/error.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>intenta de nuevo</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


</head>
<body>

  <br><br><br>
    <%= render 'layouts/error_to_render' %>

  <% flash.each do |name, msg| %>
     <%= content_tag(:div, msg, class: "alert alert-success") %>
  <% end %>


<%= yield %>


</body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewIlApp</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fontastic.s3.amazonaws.com/vCN5a39TWPcLDf8VSo5JoS/icons.css" rel="stylesheet">




</head>
<body>

  <br><br><br>
    <%= render 'layouts/landing_nav' %>


  <% flash.each do |name, msg| %>
     <%= content_tag(:div, msg, class: "alert alert-success") %>
  <% end %>


<%= yield %>


</body>
</html>